import cefast
import numpy as np
from scipy.optimize import brentq
from scipy.special import i0e, i1e

from research import c1_1_common_equation as c1

TRUE = {"D": 0.3, "A": 3.0, "tau": 200.0, "As": 1.0}


def synthetic(n=400, rho=0.6, seed=0):
    """Events generated by the common equation itself, decoded with von Mises noise of mean cosine rho."""
    rng = np.random.default_rng(seed)
    pre = rng.uniform(-np.pi, np.pi, n)
    head = pre + rng.normal(0, 1.3, n)
    lengths = rng.integers(120, 481, n)
    rel = np.angle(np.exp(1j * (head - pre)))
    sim = cefast.ring_trace(rel, lengths, 480, *(TRUE[k] for k in ("D", "A", "tau", "As")), c1.BETA, 100, 99)
    kappa = brentq(lambda k: i1e(k) / i0e(k) - rho, 1e-3, 500)
    sessions = [[] for _ in range(5)]
    for i in range(n):
        theta = pre[i] + sim[i, :lengths[i]] + rng.vonmises(0, kappa, lengths[i])
        sessions[i % 5].append({"pre": pre[i], "theta": theta, "head": np.full(lengths[i], head[i])})
    return c1.prepare(sessions)


def test_common_equation_recovers_its_parameters_and_needs_the_trace():
    events = synthetic()
    value, se, _ = c1.measured(events, np.random.default_rng(0))
    heads, lengths = c1.design(events)
    full = c1.fit(value, se, heads, lengths, ("D", "A", "tau", "As"), {}, {"D": 0.2, "A": 2.0, "tau": 300.0, "As": 0.5},
                  maxiter=120)
    none = c1.fit(value, se, heads, lengths, ("D", "As"), {"A": 0.0, "tau": 1.0}, {"D": 0.2, "As": 0.5}, maxiter=60)
    assert full["chi2_dof"] <= c1.CHI2 < none["chi2_dof"]
    assert 0.5 < full["params"]["D"] / TRUE["D"] < 2 and 0.5 < full["params"]["A"] / TRUE["A"] < 2
    assert abs(full["rho"] - 0.6) < 0.1
