import sys, os, time, numpy as np
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import fwd
rng = np.random.default_rng(fwd.SEED)
t0=time.time()
c = fwd.make_circuit(40, rng)
x = fwd.solve_x(c, (0,0,0))
print("solve time %.2fs  x shape"%(time.time()-t0), x.shape, "x range", x.min(), x.max())
mu = fwd.observe(x, "counts")
print("mu counts shape", mu.shape, "range", mu.min(), mu.max())
muc = fwd.observe(x, "ca")
print("mu ca range", muc.min(), muc.max())
# effective closed-loop timescale check
pop = x[0].mean(0)
pk = np.argmax(pop); print("peak sim idx", pk, "t=%.3f s"%(pk*fwd.SIM_DT), "peak val %.3f"%pop[pk])
t0=time.time()
I = fwd.fisher_theta(c, "counts")
print("fisher time %.2fs"%(time.time()-t0))
np.set_printoptions(precision=4, suppress=False)
print("I per trial (one mouse, n=40):\n", I)
se,corr,_ = fwd.crb_change([I]*1)
print("CRB se (1 mouse):", se)
print("corr:\n", corr)
print("channel magnitudes:", fwd.TH_GAIN, fwd.TH_EFF, fwd.TH_DEL)
