"""Freeze BA-SRM8 F2 DGP/configuration only; it executes no F2 scenario."""
from __future__ import annotations
import hashlib,json,os,platform
from pathlib import Path
import numpy as np
from funnel_core_v2 import ROOT,sha
CONFIG=ROOT/'f2-config.json';OUT=ROOT/'f2-config-receipt.json'
def canon(x):return (json.dumps(x,allow_nan=False,sort_keys=True,separators=(',',':'))+'\n').encode()
def seed(scenario,base,stream):return int.from_bytes(hashlib.sha256(f'BA-SRM8-F2-SH-v2|{scenario}|{base}|{stream}'.encode()).digest()[:8],'big')
def put(p,x):
 b=canon(x)
 with p.open('wb') as f:f.write(b);f.flush();os.fsync(f.fileno())
def main():
 streams=['clock_base','clock_gap_indices','clock_gap_sizes','skew:<redraw_index>','latent','noise','mask_mcar','block_start','artifact_select','artifact_sign']
 cfg={'schema':'BA-SRM8-F2-config-v2','behavior_loaded':False,'numerical_f2_execution':False,'N':12,'T':768,'boundaries':{'T_cal':70*768//100,'T_D':60*768//100,'zero_based_exclusive':True},'rng':{'seed_format':'uint64 big-endian first 8 SHA256 bytes UTF-8 BA-SRM8-F2-SH-v2|<scenario>|<base_seed>|<stream>','streams':streams,'example_seed':seed('ROT10',20261101,'clock_base')},'panels':{'S_cal':list(range(20261001,20261017)),'E_A':list(range(20261101,20261109)),'E_B':list(range(20261109,20261117)),'E_C':list(range(20261117,20261125)),'E_D':list(range(20261125,20261133)),'confirm':list(range(20261201,20261233))},'clock':{'dt0':0,'dt_distribution':'U(0.75,1.25)','gaps':'3 sorted distinct indices without replacement from 1..T-1; replace index order with U(4,8)','clock':'cumsum(dt)','tau0':'median(dt[1:])'},'smooth_route':{'skew':'A normal; B=A-A.T; first redraw spectral_norm>1e-12; normalize; scipy.linalg.expm','U':'expm(.35*sin(2*pi*t/256)*B)','mu':'exp(-(k-1)/(3.5+2*sin(2*pi*t/384)))','x':'U diag(sqrt(mu)) xi, xi~N(0,I)','recursion':'y[:,0]=x[:,0]; y[:,t]=(1-a_t)x[:,t]+a_t*y[:,t-1], a_t=exp(-dt[t]/6)'},'preprocess':{'noise_sd':'raw-clean first-60% prefix pooled RMS/4','quantile':'numpy.quantile(method=linear)','order_ART':'clean->Gaussian noise->artifact selection/sign/addition->mask','artifact':'1% estimate entries, +/- 10*population std(ddof=0) raw clean prefix','block':'after MCAR, per channel start integers(0,T-L+1), L=floor(.3T), zero mask'},'scenarios':{'ROT10':'smooth+irregular+MCAR10+noise','MISS30':'ROT10 MCAR30','MISS50':'ROT10 MCAR50 descriptive only','BLOCK30':'ROT10 plus block','ART10':'ROT10 plus artifact','JUMP':'U=I; t*=384; mu1:2=1 before, mu1:8=1 after, others0; irregular+MCAR10+noise','ISO_NULL':'U=I, all mu=1, irregular+MCAR10+noise','ZERO_NULL':'irregular+MCAR10, clean/noisy zero,no noise,expected abstain','REVERSE':'independent ROT10 raw from REVERSE streams; reverse values/mask; cprime[j]=c[T-1]-c[T-1-j]'},'anchors':{'A':'finite clean and estimate Q, >=100 else ABSTAIN','B':'t in A and t-1 in A, >=100 else ABSTAIN','threshold':'ISO_NULL estimate theta=linear Q.95(abs(V_est)); FAR fraction abs(V_est)>theta','jump':'argmax abs(V_est) within t*=384 +/-96 and exceeds theta'},'gates':{'F2A':'ZERO expected abstain; JUMP median rho>=.80,NMAE<=.20,FAR<=.20,detected>=4/8','F2B_C':'each scenario median rho>=.80,NMAE<=.20','F2D':'REVERSE rho>=.80,NMAE<=.20 and ISO FAR<=.20','confirm':'all recovery median rho>=.90,Q.05 rho>=.75,NMAE<=.15; ISO NMAE<=.15 mean FAR<=.10 max<=.20; JUMP32/32','ranking':'max scenario median NMAE asc, min recovery median Spearman desc, JUMP, ISO FAR asc, runtime asc, manifest ID','status':'ZERO expected abstain; recovery failure FUTILITY_KILL; cap excess DROPPED_BUDGET'},'caps':['32->24','24->20','20->16','<=16 confirm'],'promoted_ids':json.loads((ROOT/'f1-receipt-v4.json').read_text())['promoted_ids']}
 put(CONFIG,cfg);rec={'schema':'BA-SRM8-F2-config-receipt-v1','config_sha256':sha(CONFIG),'script_sha256':sha(Path(__file__)),'manifest_sha256':sha(ROOT/'candidate-manifest.json'),'core_sha256':sha(ROOT/'funnel_core_v2.py'),'f0_v3_sha256':sha(ROOT/'f0-receipt-v3.json'),'f1_v4_sha256':sha(ROOT/'f1-receipt-v4.json'),'promoted_ids_sha256':hashlib.sha256(canon(cfg['promoted_ids'])).hexdigest(),'numpy_version':np.__version__,'python_version':platform.python_version(),'behavior_loaded':False,'numerical_f2_execution':False};put(OUT,rec);print(json.dumps({'config':rec['config_sha256'],'receipt':sha(OUT)},sort_keys=True))
if __name__=='__main__':
 main()
 cfg=json.loads(CONFIG.read_text());cfg['gates']['ranking']='(E ascending, R descending, frozen ISO FAR ascending, runtime ascending, manifest ID lexical)';cfg['numeric_conventions']={'dtype':'float64','array_order':'C','draw_shapes':{'clock_base':'(T-1,)','clock_gap_indices':'(3,)','clock_gap_sizes':'(3,)','skew':'(N,N)','latent':'(N,T)','noise':'(N,T)','mask_mcar':'(N,T)','block_start':'(N,)','artifact_select':'(N,T)','artifact_sign':'(N,T)'},'comparisons':'observed rng>=p; artifact rng<0.01; sign rng<0.5 is -1; quantile linear'};put(CONFIG,cfg)
 rec=json.loads(OUT.read_text());rec.update({'config_sha256':sha(CONFIG),'script_sha256':sha(Path(__file__)),'supersedes':{'prior_config_receipt_sha256':'73ecd393aabf6456baa664bd0286c462bbfe1a2bcf61aa458ae4a872abbfbb3c','reason':'ranking tuple and numeric conventions correction'}});put(OUT,rec)
