"""Run explicit mathematical diagnostics and known-model simulated contrasts.
No empirical biological measurements are read or generated by this script.
"""
from pathlib import Path
import dataclasses, hashlib, json, math, platform
import numpy as np
import scipy
from scipy.integrate import solve_ivp
from scipy.special import logsumexp
from scipy.stats import poisson
from local_rule import Parameters, LocalPlasticity, tag_flow, rates, execute, event_map, count_moments, moment_rhs

ROOT=Path(__file__).resolve().parent
CFG=json.loads((ROOT/'protocol.json').read_text())
P=Parameters(**CFG['core'])


def true_mean_naive_example():
    # Potentiation-only subcase, explicitly not the full bidirectional hypothesis.
    # w*=.8, w0=.2, event contraction exponent 2, mean number of events 1.
    w0=.2;target=.8;k=2.;nu=1.
    true=target+(w0-target)*math.exp(nu*math.expm1(-k))
    naive=target+(w0-target)*math.exp(-nu*k)
    weak=[]
    for q in (1.,.1,.01,.001):
        n=1/q;exact=target+(w0-target)*math.exp(n*math.expm1(-q))
        limit=target+(w0-target)*math.exp(-1)
        weak.append({'dose':q,'event_count_mean':n,'exact_mean':exact,'limit':limit,'abs_difference':abs(exact-limit)})
    return {'w0':w0,'equilibrium':target,'exponent_per_event':k,'poisson_mean':nu,
            'exact_mean':true,'continuous_mean_signal':naive,'absolute_overprediction':naive-true,'weak_event_limit':weak}


def diagnostics():
    rng=np.random.default_rng(531011)
    trace_err=[];flow_err=[];mean_err=[];cov_err=[];ode_moment_err=[]
    for _ in range(CFG['math_cases']):
        pp=Parameters(tau_e_s=float(rng.uniform(.3,4)),tau_i_s=float(rng.uniform(.3,4)),tau_tag_s=float(rng.uniform(10,120)))
        e,i,t=rng.uniform(0,1,3);dt=float(rng.uniform(0,10))
        sol=solve_ivp(lambda _,y:[-y[0]/pp.tau_e_s,-y[1]/pp.tau_i_s,pp.tag_gain_per_s*y[0]*y[1]-y[2]/pp.tau_tag_s],
                      [0,dt],[e,i,t],method='DOP853',rtol=1e-11,atol=1e-13)
        direct=np.asarray(tag_flow(e,i,t,dt,pp)).reshape(3)
        trace_err.append(float(np.max(np.abs(sol.y[:,-1]-direct))))
        w=float(rng.uniform(0,1));tag=float(rng.uniform(0,2));dose=float(rng.uniform(0,5));a,b=rates(tag,pp)
        ref=solve_ivp(lambda _,y:a*(1-y)-b*y,[0,dose],[w],method='DOP853',rtol=1e-11,atol=1e-13)
        v=float(execute(w,tag,dose,pp));flow_err.append(abs(v-ref.y[0,-1]))
        assert 0<=v<=1
    for _ in range(CFG['moment_cases']):
        n=4;w=rng.uniform(.1,.9,n);tags=rng.uniform(.1,1.5,n);groups=np.zeros(n,int)
        nu=float(rng.uniform(.1,4));dose=float(rng.uniform(.1,3))
        mu,cov,naive=count_moments(w,tags,groups,nu,dose,P)
        kmax=int(poisson.ppf(1-1e-14,nu));count=np.arange(kmax+1);pr=poisson.pmf(count,nu);pr/=pr.sum()
        aa,bb=rates(tags,P);tar=aa/(aa+bb);k=dose*(aa+bb)
        values=tar+(w-tar)*np.exp(-count[:,None]*k)
        mu2=pr@values;cov2=(values-mu2).T@(pr[:,None]*(values-mu2))
        mean_err.append(float(np.max(np.abs(mu-mu2))));cov_err.append(float(np.max(np.abs(cov-cov2))))
        z0=np.r_[w,np.zeros(n*n)]
        sol=solve_ivp(lambda time,state:moment_rhs(time,state,lambda _:tags,groups,lambda _:nu,dose,P),
                      (0,1),z0,method='DOP853',rtol=1e-11,atol=1e-13)
        ode_moment_err.append(float(np.max(np.abs(sol.y[:,-1]-np.r_[mu,cov.ravel()]))))
    # Single sparse event sequence: pre and plateau build a local tag; burst is shared.
    obj=LocalPlasticity(['x0->a','x1->a','x2->b'],[0,0,1],[.1,.1,.1],[1,1,1],P)
    obj.presynaptic(0);obj.advance_to(2.);obj.instruct(0);obj.advance_to(32.)
    before=obj.weights.copy();tags=obj.tag.copy();obj.burst(0,2.)
    specificity={'weights_before':before.tolist(),'tags_before_burst':tags.tolist(),'weights_after':obj.weights.tolist(),
                 'untagged_same_branch_unchanged':bool(obj.weights[1]==before[1]),'other_branch_unchanged':bool(obj.weights[2]==before[2])}
    assert specificity['untagged_same_branch_unchanged'] and specificity['other_branch_unchanged'] and obj.weights[0]>before[0]
    zero_tag=np.array([.1,.5,.9]);assert np.array_equal(execute(zero_tag,np.zeros(3),10.,P),zero_tag)
    low_high=np.array([.1,.95]);out=execute(low_high,np.ones(2),2.,P)
    assert out[0]>.1 and out[1]<.95
    # Equal rates in the exact convolution are a finite limit.
    eq=Parameters(tau_e_s=2.,tau_i_s=2.,tau_tag_s=1.)
    _,_,eqtag=tag_flow(.7,.8,.2,2.,eq)
    expected=.2*math.exp(-2)+.7*.8*2*math.exp(-2)
    assert abs(float(eqtag)-expected)<1e-14
    assert max(trace_err)<1e-8 and max(flow_err)<1e-8 and max(mean_err)<1e-11 and max(cov_err)<1e-11 and max(ode_moment_err)<1e-8
    return {'trace_ode_cases':len(trace_err),'trace_ode_max_error':max(trace_err),'weight_flow_ode_cases':len(flow_err),
            'weight_flow_max_error':max(flow_err),'poisson_moment_cases':len(mean_err),'mean_vs_discrete_sum_error':max(mean_err),
            'cov_vs_discrete_sum_error':max(cov_err),'moment_ode_vs_closed_form_error':max(ode_moment_err),
            'synapse_specificity':specificity,'same_signal_weak_strong_result':out.tolist(),
            'average_signal_counterexample':true_mean_naive_example()}


def partition_logpdf(Y,w,tags,groups,nu,dose,sigma):
    a,b=rates(tags,P);tar=a/(a+b);k=dose*(a+b)
    cutoff=int(poisson.ppf(1-1e-13,nu));ns=np.arange(cutoff+1)
    lp=poisson.logpmf(ns,nu);lp-=logsumexp(lp)
    result=np.zeros(len(Y));const=math.log(2*math.pi*sigma*sigma)
    for group in np.unique(groups):
        ix=np.where(groups==group)[0]
        means=tar[ix]+(w[ix]-tar[ix])*np.exp(-ns[:,None]*k[ix])
        ll=-.5*np.sum((Y[:,None,ix]-means[None,:,:])**2/sigma**2+const,axis=2)
        result+=logsumexp(ll+lp[None,:],axis=1)
    return result,float(poisson.sf(cutoff,nu))


def graph_trial(seed):
    rng=np.random.default_rng(seed);n=CFG['synapses'];b=CFG['branches'];trials=CFG['trials_per_seed']
    nu=CFG['poisson_mean'];dose=CFG['pulse_dose'];sigma=CFG['measurement_noise_sd']
    group=np.repeat(np.arange(b),n//b);tags=rng.uniform(*CFG['tag_range'],n);w=rng.uniform(*CFG['initial_weight_range'],n)
    shuffled=rng.permutation(group)
    partitions={'true_branch':group,'degree_matched_shuffled':shuffled,'whole_cell_global':np.zeros(n,int),'independent_synapses':np.arange(n)}
    a,dd=rates(tags,P);target=a/(a+dd);k=dose*(a+dd)
    counts=rng.poisson(nu,size=(trials,b))
    clean=target+(w-target)*np.exp(-counts[:,group]*k)
    Y=clean+rng.normal(0,sigma,size=clean.shape)
    values={};mu_ref=None;mean_difference=0.
    for name,part in partitions.items():
        mu,cov,naive=count_moments(w,tags,part,nu,dose,P,sigma)
        if mu_ref is None:mu_ref=mu
        mean_difference=max(mean_difference,float(np.max(np.abs(mu-mu_ref))))
        lp,tail=partition_logpdf(Y,w,tags,part,nu,dose,sigma)
        values[name]={'nll_per_synapse':float(-lp.mean()/n),'marginal_mean_mse':float(np.mean((Y-mu)**2)),
                      'mixture_excluded_tail_mass':tail}
    # Rows are complete multivariate trials; no marginal datapoints are counted as independent trials.
    return {'seed':seed,'trials':trials,'synapses_per_trial':n,'results':values,'analytic_mean_difference_between_partitions':mean_difference,
            'same_degree_multiset':bool(sorted(np.bincount(group))==sorted(np.bincount(shuffled))),
            'naive_mean_bias_rms':float(np.sqrt(np.mean((mu_ref-naive)**2)))},Y,w,tags,group,shuffled


def time_varying_mc():
    # Independent event-time simulation, not a check against the same event integrator.
    rng=np.random.default_rng(381901);N=65536;n=4;groups=np.array([0,0,1,1]);H=30.;rate=.1;dose=2.
    w0=np.array([.15,.3,.85,.7]);T0=np.array([.8,.5,.9,.6]);tau=60.
    sol=solve_ivp(lambda t,z:moment_rhs(t,z,lambda s:T0*np.exp(-s/tau),groups,lambda _:rate,dose,P),
                  (0,H),np.r_[w0,np.zeros(n*n)],method='DOP853',rtol=1e-11,atol=1e-13)
    mu=sol.y[:n,-1];cov=sol.y[n:,-1].reshape(n,n)
    W=np.tile(w0,(N,1))
    for branch in range(2):
        ix=np.where(groups==branch)[0];counts=rng.poisson(rate*H,N);num=int(counts.max())
        times=np.sort(rng.uniform(0,H,size=(N,num)),axis=1)
        # Conditional on count=n, the FIRST n of num sorted samples would be WRONG.
        # Fill unused events with +inf before sorting so each row has n iid Uniform events.
        raw=rng.uniform(0,H,size=(N,num));raw[np.arange(num)[None,:]>=counts[:,None]]=np.inf
        times=np.sort(raw,axis=1)
        for j in range(num):
            active=np.where(np.isfinite(times[:,j]))[0]
            tags=T0[ix][None,:]*np.exp(-times[active,j,None]/tau)
            W[np.ix_(active,ix)]=execute(W[np.ix_(active,ix)],tags,dose,P)
    em=W.mean(axis=0);ec=np.cov(W,rowvar=False,bias=True)
    se=np.sqrt(np.diag(cov)/N)
    return {'trials':N,'tag_decay_during_execution':True,'analytic_means':mu.tolist(),'empirical_means':em.tolist(),
            'mean_error_in_standard_errors':((em-mu)/se).tolist(),'max_covariance_error':float(np.max(np.abs(ec-cov))),
            'note':'Monte Carlo differences are sampling error; this is not a machine precision assertion or biological sample.'}


def main():
    diag=diagnostics();rows=[];snapshots={}
    for seed in CFG['seeds']:
        row,Y,w,tags,group,shuffled=graph_trial(seed);rows.append(row)
        snapshots[f'{seed}_observed']=Y;snapshots[f'{seed}_weights']=w;snapshots[f'{seed}_tags']=tags
        snapshots[f'{seed}_groups']=group;snapshots[f'{seed}_shuffled']=shuffled
    np.savez_compressed(ROOT/'simulated_trials.npz',**snapshots)
    summaries={name:{'mean_nll_per_synapse':float(np.mean([r['results'][name]['nll_per_synapse'] for r in rows])),
                      'mean_marginal_mse':float(np.mean([r['results'][name]['marginal_mean_mse'] for r in rows]))}
               for name in CFG['comparison_partitions']}
    differences={}
    for name in CFG['comparison_partitions'][1:]:
        dif=np.array([r['results'][name]['nll_per_synapse']-r['results']['true_branch']['nll_per_synapse'] for r in rows])
        differences[name]={'mean_excess_nll_per_synapse':float(dif.mean()),'true_partition_better_seeds':int((dif>0).sum()),'total_seeds':len(rows)}
    result={'scope':'MODEL_INTERNAL_DIAGNOSTIC_ONLY; new biological specimens=0; no test of human-brain algorithm completed',
            'protocol_sha256':hashlib.sha256((ROOT/'protocol.json').read_bytes()).hexdigest(),
            'environment':{'python':platform.python_version(),'numpy':np.__version__,'scipy':scipy.__version__},
            'diagnostics':diag,'graph_summary':summaries,'graph_differences':differences,
            'total_simulated_trials':len(rows)*CFG['trials_per_seed'],'time_varying_jump_check':time_varying_mc(),'rows':rows}
    (ROOT/'results.json').write_text(json.dumps(result,ensure_ascii=False,indent=2,allow_nan=False)+'\n')
    print(json.dumps({k:v for k,v in result.items() if k!='rows'},ensure_ascii=False,indent=2))

if __name__=='__main__':main()
